name: johndahlman
favicon: null
layout_spectrum: 0.9055649
typography_spectrum: 0.75965
title: "John Dahlman's home on the web"
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#ACACAC'
    - '#393939'
    - '#777777'
    - '#FCFCFC'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
