name: johndahlman
favicon: null
layout_spectrum: 0.97334
typography_spectrum: 0.75965
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#33322e'
    - '#000207'
    - '#c5bfa1'
    - '#fefefe'
    - '#901fd1'
  brandStrength: 0.27516121859662235
  lightness: 0.9196043568663299
  saturation: 0.9538343586027622
  rhythmicContrast: 0.5354217984713614
purpose: []
